[server]
headless = true

[client]
showSidebarNavigation = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#111827"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F4F6"
textColor = "#111827"
